---
title: "Dark Kinase Expression in ARCHS4 Data"
output: github_document
---

```{r libraries, echo=F, include=F}
library(rhdf5)
library(tidyverse)
```

```{r download, include=F, eval=F}
download.file('https://s3.amazonaws.com/mssm-seq-matrix/human_matrix.h5','human_matrix.h5')
```

```{r loading, include=F}
meta_data = h5read('human_matrix.h5','/meta')
```

# Cell Line Counts

```{r processing}
cell_line = c("AsPC1","BxPC3","Capan1","Capan2","CFPAC-1","HPAF-II","Hs766T",
              "Miapaca","Panc-1","SW1990","A427","A549","H1299","H1395",
              "H1703","H1703","H2126","H2170","H2228","H23","H358","H441",
              "H520","H522","H727","SK-MES","SW900")

cell_line_data = as.data.frame(
  meta_data[c("Sample_characteristics_ch1",
              "Sample_description",
              "Sample_source_name_ch1",
              "Sample_title",
              "Sample_geo_accession")])

hit_sets = list()
hit_counts = list()

for (this_line in cell_line) {
  title_hits = cell_line_data %>%
    filter(grepl(this_line,Sample_title,ignore.case = T) |
           grepl(this_line,Sample_characteristics_ch1,ignore.case = T) |
           grepl(this_line,Sample_description,ignore.case = T) |
           grepl(this_line,Sample_source_name_ch1,ignore.case = T))
  
  control_hits = title_hits %>%
    filter(grepl('control|ctrl|DMSO',Sample_title,ignore.case = T) |
           grepl('control|ctrl|DMSO',Sample_characteristics_ch1,ignore.case = T) |
           grepl('control|ctrl|DMSO',Sample_description,ignore.case = T) |
           grepl('control|ctrl|DMSO',Sample_source_name_ch1,ignore.case = T))
  
  hit_sets$this_line = c(hit_sets$this_line,this_line)
  hit_sets$title = c(hit_sets$title,title_hits)
  hit_sets$control = c(hit_sets$control,control_hits)
  
  hit_counts$cell_line = c(hit_counts$cell_line, this_line)
  hit_counts$line_counts = c(hit_counts$line_counts, dim(title_hits)[1])
  hit_counts$control_counts = c(hit_counts$control_counts, dim(control_hits)[1])
}
hit_counts = as.data.frame(hit_counts)

hit_counts = hit_counts %>% 
  select(cell_line,line_counts,control_counts) %>% 
  arrange(desc(control_counts))
```

# Cell Line Count Table

For reference, there are `r sum(hit_counts$line_counts)` hits to the list of cell lines, with `r sum(hit_counts$control_counts)` matching either 'control', 'ctrl' or 'DMSO'.

```{r}
knitr::kable(hit_counts)
```